# Generated by Django 4.2.3 on 2023-07-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
    ]
